tagline: 
  fr: "Produit phare"
title: 
  fr: "ZERO : la gestion des refus d’assurance réinventée"
description: 
  fr: "ZERO révolutionne la manière dont les organisations de santé traitent les refus d’assurance. Notre plateforme intelligente structure et automatise les processus de gestion des refus tout en offrant une visibilité claire et complète sur le cycle de facturation."
cta_button: 
  fr: "En savoir plus sur ZERO"
features:
  fr:
    - "Catégorisation automatisés des refus"
    - "Routage intelligent des flux de travail et attribution des tâches"
    - "Tableau de bord complet de suivi des factures"
    - "Analyses et rapports en temps réel"
    - "Intégration transparente avec les systèmes de facturation existants"
    - "Réduction des délais de traitement et des erreurs manuelles"

stats:
  fr:
    - number: "25%"
      label: "Traitement des refus plus rapide"
    - number: "87%"
      label: "Taux de satisfaction des utilisateurs"
    - number: "99%"
      label: "Réduction du temps passé au suivi"
    - number: "97%"
      label: "Précision des données"

features_showcase:
  fr:
    - title: "Suivi des refus"
      description: "Visualisez en temps réel la situation globale de vos refus d'assurance. Notre tableau de bord intuitif vous offre une vue d'ensemble complète pour un pilotage efficace de vos dossiers en attente."
      image_path: "/assets/images/pilotage_zero.PNG"
      image_desription: "Aperçu du tableau de bord de suivi"
    - title: "Analyse des catégories"
      description: "Identifiez les tendances et les causes récurrentes de refus grâce à notre système d'analyse avancé. Catégorisez automatiquement les refus et corrigez les erreurs dans votre processus de facturation pour réduire les rejets futurs."
      image_path: "/assets/images/analytic_classifications.PNG"
      image_desription: "Tableau d'analyse des catégories de refus"
    - title: "Chronologie"
      description: "Tracez l'historique complet de chaque refus avec notre système de chronologie détaillé. Suivez toutes les actions effectuées, même après une refacturation, et gardez une traçabilité parfaite de l'état de vos dossiers."
      image_path: "/assets/images/chronology.PNG"
      image_desription: "Vue chronologique des actions"

contact:
  fr:
    title: "Prêt à en savoir plus sur ZERO ?"
    description: "Discutons de la manière dont nous pouvons vous aider à optimiser vos flux de travail concernant vos contestations."
    email: "contact@sanabill.ch"
