tagline: 
  fr: "Produit phare"
title: 
  fr: "ZERO : la gestion des refus d’assurance réinventée"
description: 
  fr: "ZERO révolutionne la manière dont les organisations de santé traitent les refus d’assurance. Notre plateforme intelligente structure et automatise les processus de gestion des refus tout en offrant une visibilité claire et complète sur le cycle de facturation."
cta_button: 
  fr: "En savoir plus sur ZERO"
features:
  fr:
    - "Traitement et catégorisation automatisés des refus"
    - "Routage intelligent des flux de travail et attribution des tâches"
    - "Tableau de bord complet de suivi des factures"
    - "Analyses et rapports en temps réel"
    - "Intégration transparente avec les systèmes de facturation existants"
    - "Réduction des délais de traitement et des erreurs manuelles"

stats:
  fr:
    - number: "25%"
      label: "Traitement des refus plus rapide"
    - number: "87%"
      label: "Taux de satisfaction des utilisateurs"
    - number: "99%"
      label: "Réduction du temps passé au suivi"
    - number: "97%"
      label: "Précision des données"

